### ISSUE TITLE
Add VS Code Integration section in the Document Processing documentation

### ISSUE THREAD

**Issue by mariaterzieva12** [telerik/document-processing-docs#407]
**What would you like to see added, improved or changed?**
For Q2 2024 release , we are adding a Document Processing Configuration Wizard for **Telerik UI for Blazor** and **Telerik UI for ASP.NET Core** extensions for Visual Studio Code. With this change , the Document Processing documentation needs update, by adding a new section for VS Code Integration. 

**Here are the changes that affects the clients:**
 -  The Configuration wizard will help the clients to easy add a reference to the Telerik Document Processing Libraries (DPL) packages in an existing **Telerik UI for Blazor**  or **Telerik UI for ASP.NET Core** applications. The wizards are included in the **Telerik UI for Blazor Visual Studio Code extension** and **Telerik UI for ASP.NET Core Visual Studio Code extension**. 

Additional resources that might be helpful: 
 - The Marketplace documentation:
 -- Blazor - https://github.com/telerik/vscode-extensions/blob/main/vscode-extension-blazor/README.md#document-processing-libraries-configuration-wizard
-- ASP.NET Core - https://github.com/telerik/vscode-extensions/blob/main/vscode-extension-aspnetcore/README.md#document-processing-libraries-configuration-wizard
- I am attaching also the .md file that I prepared for Blazor documentation , but is still in progress. 
[dpl-wizard.md](https://github.com/telerik/document-processing-docs/files/15064280/dpl-wizard.md)

 **Deadlines**  
This is needed for the Q2 release.

**Comment by dessyordanova** [comment]
This is the preview in the test environment: https://testdocs.telerik.com/devtools/document-processing/integration/integration-with-vs-code
